### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by he5050** [364734461/Koa-NextJS-TypeScript#1]
刚下载试了下跑不起项目

**Comment by 364734461** [comment]
如果没有猜错，你使用的应该是windows环境吧？
你可以尝试新建 nodemon.json 文件：
`{
  "watch": ["config/*.js", "server/**/*.ts", "utils/*.js"],
  "ext": "ts",
  "exec": "ts-node --project tsconfig.server.json server/index.ts"
}`
删除package.json里面的nodemon配置。再运行试试？
（因为这个项目好久没有更新了，当时是linux环境下开发的，没有试验windows环境。看过几天我再抽点时间出来更新一下，这个项目的代码，优化以及新增了不少东西 ^_^）

**Comment by he5050** [comment]
已经解决了谢谢
